---
id: mozilla-japan-seminar
base_name: firefox-in-corporations
tags:
- Mozilla
- Firefox
presentation_date: 2016/3/16
version: 2016.03.16
licenses: []
slideshare_id: mozilla-japan-seminar-firefox-in-corporations
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: 結城洋志
  email: yuki@clear-code.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: 
